name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 1.0.7
author: Darshan Narayanaswamy<noeatsleepdev@gmail.com>
homepage: https://github.com/DarshanGowda0/GeoFlutterFire

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.0
  cloud_firestore: ^0.9.0+1
  rxdart: ^0.20.0

flutter:
  plugin:
    androidPackage: com.noeatsleepdev.geoflutterfire
    pluginClass: GeoflutterfirePlugin
